name: main

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  run-benchmark:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - uses: ./.github/action/setup-ccache
        with:
          size: 512M
          key: ccache-${{ matrix.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ccache-${{ matrix.os }}-build-
      - run: npm run build
      - run: npm run setup
      - run: npm run run
      - run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "daily: update benchmark results $(date)" || echo "no changes to commit"
